function init(self)
	msg.post('.', 'acquire_input_focus')
end

function final(self)
	msg.post('.', 'release_input_focus')
end

function on_input(self, action_id, action)
	if action.pressed then
		if gui.pick_node(gui.get_node('enter'), action.x, action.y) then
			msg.post('controller:/manager', 'load_game')
		elseif gui.pick_node(gui.get_node('exit'), action.x, action.y) then
			os.exit()
		end
	end
end
