function init(self)
	msg.post('.', 'acquire_input_focus')
end

function final(self)
	msg.post('.', 'release_input_focus')
end

function on_input(self, action_id, action)
	if action.pressed then
		if gui.pick_node(gui.get_node('resume'), action.x, action.y) then
			msg.post('play:/manager', 'resume')
		elseif gui.pick_node(gui.get_node('exit_game'), action.x, action.y) then
			msg.post('controller:/manager', 'show_menu')
		end
	end
end
